import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

test('Android UTS attachment plugin exposes gallery camera file character-card world-book and backup selection', async () => {
  const [manifest, pluginManifest, interfaceSource, androidSource] = await Promise.all([
    readFile(new URL('../uni_modules/ai-chat-attachment-picker/package.json', import.meta.url), 'utf8'),
    readFile(new URL('../uni_modules/ai-chat-attachment-picker/utssdk/app-android/AndroidManifest.xml', import.meta.url), 'utf8'),
    readFile(new URL('../uni_modules/ai-chat-attachment-picker/utssdk/interface.uts', import.meta.url), 'utf8'),
    readFile(new URL('../uni_modules/ai-chat-attachment-picker/utssdk/app-android/index.uts', import.meta.url), 'utf8')
  ])

  assert.match(manifest, /aiChatPickAttachments/)
  assert.match(manifest, /aiChatWriteDownloadFile/)
  assert.match(interfaceSource, /aiChatPickAttachments/)
  assert.match(interfaceSource, /aiChatWriteDownloadFile/)
  assert.match(androidSource, /Intent\.ACTION_OPEN_DOCUMENT/)
  assert.match(androidSource, /Intent\.FLAG_GRANT_READ_URI_PERMISSION/)
  assert.match(androidSource, /MediaStore\.ACTION_IMAGE_CAPTURE/)
  assert.match(androidSource, /UTSAndroid\.onAppActivityResult/)
  assert.match(androidSource, /['"]character-card['"]/)
  assert.match(androidSource, /['"]image-file['"]/)
  assert.match(androidSource, /options\.mode == ['"]image-file['"]\) files\.push\(prepareImage\(resolver, uri\)\)/)
  assert.ok(androidSource.indexOf("options.mode == 'image-file'") < androidSource.indexOf("options.mode == 'file'"))
  assert.match(androidSource, /['"]character-card-file['"]/)
  assert.match(androidSource, /['"]character-card-gallery['"]/)
  assert.match(androidSource, /else if \(isCharacterCardMode\(options\.mode\)\)\s*\{[\s\S]*?intent\.setType\(['"]\*\/\*['"]\)/)
  assert.doesNotMatch(androidSource, /intent\.setType\(['"]image\/png['"]\)/)
  assert.match(androidSource, /new Intent\(Intent\.ACTION_PICK\)/)
  assert.match(androidSource, /MediaStore\.Images\.Media\.EXTERNAL_CONTENT_URI/)
  assert.match(androidSource, /function startImageGalleryPicker\(options\s*:\s*AiChatPickAttachmentsOptions\)/)
  assert.match(androidSource, /intent\.putExtra\(Intent\.EXTRA_ALLOW_MULTIPLE, options\.maxCount > 1\)/)
  assert.match(androidSource, /options\.mode == ['"]image['"]\) startImageGalleryPicker\(options\)/)
  assert.match(androidSource, /startCharacterCardGalleryPicker\(\)/)
  assert.match(androidSource, /selectedName\.toLowerCase\(\)\.endsWith\(['"]\.png['"]\)\s*\?\s*selectedName\s*:\s*selectedName\s*\+\s*['"]\.png['"]/)
  assert.match(androidSource, /MAX_CHARACTER_CARD_BYTES\s*:\s*Int\s*=\s*50\s*\*\s*1024\s*\*\s*1024/)
  assert.match(androidSource, /data:image\/png;base64/)
  assert.match(androidSource, /prepareCharacterCard/)
  assert.match(androidSource, /['"]world-book['"]/)
  assert.match(androidSource, /bytes\[0\]\.toInt\(\)\s*!=\s*-119/)
  assert.match(androidSource, /MAX_WORLD_BOOK_BYTES\s*:\s*Int\s*=\s*5\s*\*\s*1024\s*\*\s*1024/)
  assert.match(androidSource, /prepareWorldBook/)
  assert.match(androidSource, /['"]backup-json['"]/)
  assert.match(androidSource, /MAX_BACKUP_JSON_BYTES\s*:\s*Int\s*=\s*50\s*\*\s*1024\s*\*\s*1024/)
  assert.match(androidSource, /prepareBackupJson/)
  assert.match(androidSource, /resolveActivity\(activity\.getPackageManager\(\)\)/)
  assert.match(androidSource, /Build\.VERSION\.SDK_INT\s*<=\s*Build\.VERSION_CODES\.P/)
  assert.match(androidSource, /permissions\.push\(['"]android\.permission\.WRITE_EXTERNAL_STORAGE['"]\)/)
  assert.match(pluginManifest, /WRITE_EXTERNAL_STORAGE[^>]+maxSdkVersion="28"/)
  assert.doesNotMatch(pluginManifest, /READ_EXTERNAL_STORAGE/)
})

test('Android UTS attachment plugin writes bounded binary exports into public Downloads', async () => {
  const [interfaceSource, androidSource, mainSource] = await Promise.all([
    readFile(new URL('../uni_modules/ai-chat-attachment-picker/utssdk/interface.uts', import.meta.url), 'utf8'),
    readFile(new URL('../uni_modules/ai-chat-attachment-picker/utssdk/app-android/index.uts', import.meta.url), 'utf8'),
    readFile(new URL('../main.js', import.meta.url), 'utf8')
  ])

  assert.match(interfaceSource, /AiChatWriteDownloadFileOptions/)
  assert.match(interfaceSource, /operation\s*:\s*string/)
  assert.match(interfaceSource, /fileName\s*\?:\s*string/)
  assert.match(interfaceSource, /base64\s*\?:\s*string/)
  assert.match(androidSource, /MAX_DOWNLOAD_BYTES\s*:\s*Int\s*=\s*50\s*\*\s*1024\s*\*\s*1024/)
  assert.match(androidSource, /MAX_DOWNLOAD_FILE_NAME_BYTES\s*:\s*Int\s*=\s*255/)
  assert.match(androidSource, /toByteArray\(StandardCharsets\.UTF_8\)\.size\s*>\s*MAX_DOWNLOAD_FILE_NAME_BYTES/)
  assert.match(androidSource, /Base64\.decode\([^,]+, Base64\.NO_WRAP\)/)
  assert.match(androidSource, /MediaStore\.Downloads\.EXTERNAL_CONTENT_URI/)
  assert.match(androidSource, /MediaStore\.Downloads\.RELATIVE_PATH/)
  assert.match(androidSource, /Environment\.DIRECTORY_DOWNLOADS\s*\+\s*['"]\/['"]\s*\+\s*DOWNLOAD_FOLDER/)
  assert.match(androidSource, /MediaStore\.Downloads\.IS_PENDING/)
  assert.match(androidSource, /deleteMediaUriQuietly/)
  assert.match(androidSource, /new FileOutputStream\(partial, false\)/)
  assert.match(androidSource, /LEGACY_PART_PREFIX\s*\+\s*sessionId\s*\+\s*LEGACY_PART_SUFFIX/)
  assert.doesNotMatch(androidSource, /['"]\.['"]\s*\+\s*fileName\s*\+\s*['"]\.['"]\s*\+\s*sessionId/)
  assert.match(androidSource, /cleanupLegacyDownloadPartials\(folder,\s*!downloadSessions\.isEmpty\(\)\)/)
  assert.match(androidSource, /cleanupModernDownloadPartials\(resolver,\s*context\.getPackageName\(\),\s*!downloadSessions\.isEmpty\(\)\)/)
  assert.match(androidSource, /MediaStore\.Downloads\.OWNER_PACKAGE_NAME\s*\+\s*['"] = \?['"]/)
  assert.doesNotMatch(androidSource, /MediaStore\.Downloads\.RELATIVE_PATH\s*\+\s*['"] LIKE \?['"]/)
  assert.match(androidSource, /modernDownloadCleanupComplete\s*=\s*true[\s\S]*catch \(ignored\)/)
  assert.match(androidSource, /WRITE_EXTERNAL_STORAGE/)
  assert.match(androidSource, /Executors\.newSingleThreadExecutor\(\)/)
  assert.match(androidSource, /['"]\.part['"]/)
  assert.match(androidSource, /renameTo\(destination\)/)
  assert.match(androidSource, /operation == ['"]append['"]/)
  assert.match(androidSource, /operation == ['"]commit['"]/)
  assert.match(androidSource, /const session\s*=\s*downloadSessions\.get\(sessionId\)[\s\S]*session\?\.abort\(true\)[\s\S]*downloadSessions\.remove\(sessionId\)/)
  assert.match(androidSource, /if \(operation != ['"]abort['"]\)[\s\S]*cleanup!\.abort\(true\)[\s\S]*downloadSessions\.remove\(cleanup!\.sessionId\)/)
  assert.match(androidSource, /result\s*=\s*\{\s*sessionId,\s*filePath:\s*['"]['"],\s*byteSize:\s*0\s*\}/)
  assert.match(androidSource, /error\.toString\(\)/)
  assert.match(mainSource, /aiChatWriteDownloadFile/)
  assert.match(mainSource, /__aiChatNativeApis\s*=\s*\{[\s\S]*aiChatWriteDownloadFile/)
})

test('Android UTS attachment plugin prepares bounded images and strict UTF-8 text', async () => {
  const source = await readFile(new URL('../uni_modules/ai-chat-attachment-picker/utssdk/app-android/index.uts', import.meta.url), 'utf8')

  assert.match(source, /BitmapFactory\.decodeByteArray/)
  assert.match(source, /MAX_IMAGE_DIMENSION\s*:\s*Int\s*=\s*1600/)
  assert.match(source, /MAX_IMAGE_BYTES\s*:\s*Int\s*=\s*2\s*\*\s*1024\s*\*\s*1024/)
  assert.match(source, /\[86, 78, 70, 62, 54\]/)
  assert.match(source, /CodingErrorAction\.REPORT/)
  assert.match(source, /MAX_TEXT_BYTES\s*:\s*Int\s*=\s*200\s*\*\s*1024/)
  assert.match(source, /arrayOf\(OpenableColumns\.DISPLAY_NAME\)/)
  assert.match(source, /const width\s*:\s*Int\s*=\s*Math\.max\([^\n]+\)\.toInt\(\)/)
  assert.match(source, /let y\s*:\s*Int\s*=\s*0/)
  assert.match(source, /let index\s*:\s*Int\s*=\s*0/)
  assert.match(source, /import CompressFormat from ['"]android\.graphics\.Bitmap\.CompressFormat['"]/)
  assert.match(source, /format\s*:\s*CompressFormat, quality\s*:\s*Int/)
  assert.match(source, /message\s*:\s*string\s*=\s*['"]['"]/)
})
